### ISSUE TITLE
difficulty input not documented

### ISSUE THREAD

**Issue by LeonardoGentile** [mikermcneil/machinepack-passwords#1]
The `difficulty` input is not documented, how is it supposed to work?

**Comment by sgress454** [comment]
It looks like that input was removed from the machine; are you just asking because it's referenced in the code?  

In an earlier version of the pack it had something to do with the number of times the password was hashed, but we moved to a different native version of bcrypt which doesn't have that option.  Looks like we just neglected to remove it from the code, so thanks for the heads up!

**Comment by LeonardoGentile** [comment]
I was following a tutorial and it was mentioned that input. So I went to http://node-machine.org/machinepack-passwords/encrypt-password that took me here where I found a reference to `difficulty` but nothing more.

Thanks for your time :+1:

**Comment by sgress454** [comment]
Thanks for the heads up @LeonardoGentile, I see what you're talking about.  We'll update the tutorial.
